### ISSUE TITLE
Implement tarothon feature.

### ISSUE THREAD

**Issue by gillessed** [gillessed/palantarot#10]
Add ability to create, track and save tarothons.

**Comment by hensed** [comment]
This should be highest in priority, Fosco and I are discussing a tarothon in the next coming weeks.

**Comment by gillessed** [comment]
Alright, I'm starting on this tonight. I'll close the issue once it's live.

**Comment by gillessed** [comment]
Also, @hensed, I'm going to be able to retroactively add old tarothons too, so if you can find out the dates of past tarothons, we can add them in for posterity.

**Comment by gillessed** [comment]
We should be good to go here. Feature is live.
