### ISSUE TITLE
Calculate point flows

### ISSUE THREAD

**Issue by gillessed** [gillessed/palantarot#39]
For a given player, calculate who won the most points in games that player lost, and who lost the most points in games that player won.

In essence, who are you taking points from, and who are you losing points from.

This should be done on a monthly basis.

**Comment by hensed** [comment]
I did this one, it was not popular.

**Comment by gillessed** [comment]
Yeah I think one of the issues was that it was quite opaque. It wasn't clear how exactly the number was being computed. I love the idea, and I want to bring it back, but I think the goal should be to make people understand what is actually being computed.

Do you think that's the case?

**Comment by hensed** [comment]
Good point, it may have been too vague, and calculation too square and boring. 

--Dana

**Comment by hensed** [comment]
I was picking out a player’s total wins in any role, then calculating the top three people with the total-most losses on those wins. Did a monthly total and a on-going tally. 

--Dana

**Comment by gillessed** [comment]
That sounds like what I'd expect to do. I'll have to think on this one.

**Comment by gillessed** [comment]
Done!
